version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db